### ISSUE TITLE
404 on getting prebuild for macOS

### ISSUE THREAD

**Issue by gabrielfnogueira** [thiagoelg/node-printer#12]
Hey, is it possible to publish the prebuild for `node-printer-v0.5.2-electron-v75-darwin-x64.tar.gz`? I'm getting 404.

Also, I noticed there's an open PR to make it work with electron 8. Any plans to merge it? I'd love to help if needed 😁

**Comment by thiagoelg** [comment]
Hey @gabrielfnogueira, I've merged @tauu's PR and updated the build pipelines on Travis and Appveyor, creating the v0.5.3 release and the electron-v75 build, you're welcome to check it out.

I haven't tested the new versions, so I'll leave this issue open if you find any problems.
