### ISSUE TITLE
modul not found?

### ISSUE THREAD

**Issue by tripower** [thiagoelg/node-printer#18]
Hello

I want to try an example with printDirect of a PDF 
but I get this error

default printer name: PDF24 (umgeleitet 1)
**error on printing: Error: StartDocPrinterW error: code: 126, message: Das angegebene Modul wurde nicht gefunden.**

any ideas whats going wrong?

regards
Klaus

**Comment by darkworks** [comment]
same happening to me too

**Comment by bcotteret** [comment]
I don't think you can print PDF
with the original [tojocky/node-printer](https://github.com/tojocky/node-printer) 
you will have to use [node-pdfium](https://github.com/tojocky/node-pdfium), which only works on windows or better
: [pdf-to-printer](https://github.com/artiebits/pdf-to-printer)
