### ISSUE TITLE
Error: Cannot find module '../lib'

### ISSUE THREAD

**Issue by Mohini89** [thiagoelg/node-printer#22]
Error: Cannot find module '../lib'

can you please tell what's the library name to be imported

**Comment by Mohini89** [comment]
trying to import it below code 

"var printerDriver = require("@thiagoelg/node-printer");"

But getting an  error "Could not find a declaration file for module '@thiagoelg/node-printer'. '/home/vouched4u/Desktop/Deployments/Dev/Marketing/node_modules/@thiagoelg/node-printer/lib/printer.js' implicitly has an 'any' type."

**Comment by thiagoelg** [comment]
Hi, this lib doesn't have typescript typings yet, so that's why you're getting this error.
