### ISSUE TITLE
Could not detect abi for version 14.2.2 and runtime electron. 

### ISSUE THREAD

**Issue by adamwpe** [thiagoelg/node-printer#30]
I'm trying to update my electron application from 13 to 14, and now this package does not installed:

Error: Could not detect abi for version 14.2.2 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron.

Any ideas?

**Comment by 40x** [comment]
I have the same issue, any suggestions?

**Comment by TomHoenderdos** [comment]
For me this command helped solving this error: `npx uuaw node-abi`

**Comment by thiagoelg** [comment]
Hello everyone!
Just release `0.5.7` with new builds for Node up to version 17 and Electron up to 17 (Node ABI 102 and Electron ABI 101).

Let me know if this version fixes the problem for you.

**Comment by adamwpe** [comment]
Thanks @thiagoelg - it seems to have worked :).

I did need to install 'patch-package' in my package.json to it working.
