### ISSUE TITLE
Error: Module did not self-register

### ISSUE THREAD

**Issue by KirisakiAria** [thiagoelg/node-printer#31]
Node 14.4.0

Vue 2.6.11 + Electron 13.0

I added electron using the "vue add electron" command in vue-cli, the project is running well.
But when I import node-printer, the following exception will be prompted.

Error: Module did not self-register: '\\?\D:\Project\printer\node_modules\@thiagoelg\node-printer\lib\node_printer.node'.

![2](https://user-images.githubusercontent.com/20788476/145745758-206e01e4-1909-46f9-bcdf-ba63c57e2123.png)
This print is a method bound to the button.

![1](https://user-images.githubusercontent.com/20788476/145745584-c5501ba2-adb9-4f86-ad46-378803313078.png)

**Comment by gathrlabs** [comment]
Hey @KirisakiAria, did you find a solution for this issue?

**Comment by joserick** [comment]
Solution:

- npm i @electron/rebuild
- .\node_modules\.bin\electron-rebuild
