### ISSUE TITLE
patch-package not found error when installing v0.5.7

### ISSUE THREAD

**Issue by mariano-filipe** [thiagoelg/node-printer#37]
Hi, I just tried upgrading to v0.5.7 but yarn is giving me an error during the the build step of this package at version 0.5.7. The full logs are as follow:

```
# This file contains the result of Yarn building a package (@thiagoelg/node-printer@npm:0.5.7)
# Script name: postinstall

command not found: patch-package
```

I think that to solve this you need to include this `patch-package` in the dependencies of this project since it's used by the `postinstall` hook.

**Comment by thiagoelg** [comment]
Good catch, `patch-package` was installed as a devDependency, but that's not installed when an app uses this library, so I moved it to the dependencies list.

**Comment by Price3258** [comment]
thank you really
