### ISSUE TITLE
add more maintainers

### ISSUE THREAD

**Issue by sibelius** [thiagoelg/node-printer#71]
can you add myself as a contributor to this package ?

**Comment by thiagoelg** [comment]
Hello!
Sorry this repo is kind of abandoned, I don't have a thermal printer to test things anymore.
Sent you an invite to be a contributor, let me know if you need anything else!

**Comment by sibelius** [comment]
we moved to https://github.com/grandchef/node-printer

**Comment by AndresGX** [comment]
@thiagoelg have you any example how to print images with raw type?
