### ISSUE TITLE
Does not print in windows, please help

### ISSUE THREAD

**Issue by vadhack** [thiagoelg/node-printer#8]
Hello, 

i installed this package and all right but when i send a print (printDirect) job execute successfully but the printer do nothing, 

I tested in Linux and all right,  the problem is in Windows 10, i need help, please can you guide me?

this is my code for test:

`

printer = require "@thiagoelg/node-printer"

printerName = 'EPSON LX-350' 

print = ->
    printer.printDirect
        data: Buffer.from 'Simple Text'
        printer: printerName
        type: 'RAW'
        success: (jobID) ->
            console.log('sent to printer with ID: ' + jobID)
        error: (err) ->
            console.log(err)
        
print()
`

**Comment by thiagoelg** [comment]
Hi! Sorry it took me this long to reply.
Have you managed to print successfully? If not, can you send the output of `printer.getPrinters()`?

**Comment by tsnyamochir** [comment]
> Hello,
> 
> i installed this package and all right but when i send a print (printDirect) job execute successfully but the printer do nothing,
> 
> I tested in Linux and all right, the problem is in Windows 10, i need help, please can you guide me?
> 
> this is my code for test:
> 
> `
> 
> printer = require "@thiagoelg/node-printer"
> 
> printerName = 'EPSON LX-350'
> 
> print = ->
> printer.printDirect
> data: Buffer.from 'Simple Text'
> printer: printerName
> type: 'RAW'
> success: (jobID) ->
> console.log('sent to printer with ID: ' + jobID)
> error: (err) ->
> console.log(err)
> 
> print()
> `

Hello, have you solved this issue?
